### ISSUE TITLE
Support for loading data from meters

### ISSUE THREAD

**Issue by drfraser** [push-things/dj-diabetes#6]
Hi,

I'm diabetic and will take a look at this for sure - I know Django and something I can play with would be great. My greatest pain point has always been the manual recording of data in a logbook and doing this thru a GUI doesn't improve things (it wasn't clear from the description if this supports data download).

Software I recently looked at, OneTouch's OTDMS (finally decided to download it), is generally awful (poor graphics and UI) which is probably why they have discontinued it and are trying to force users to use their web based app (no, I'm not sending my health data to god knows what insurance company to be resold). The iOS apps I've looked at also have this problem of needing to manually input data (and a lot have bad UIs).

The Freestyle Libre software is pretty nice (I can send you screenshots if you want), but their CGM things (that use Bluetooth) are a bit too flaky I think - I returned too many in a row to justify keep buying them.  I just got a new GlucoRx meter but haven't started using it so don't know how nice their software is yet.

For info on dealing with meters, https://openaps.org/ would be a starting point. There is a whole bunch of diabetes software out there, but I'm not sure about the amount of info for dealing with hardware/meters (just have stuck with the OneTouch for too long).

So even some sort of import option to import a csv file (assuming one can get that in some fashion from your meter/other software) would be useful.

**Comment by foxmask** [comment]
Thanks. I'll have a look at all of this. If i could help with improvements that will be a pleasure

**Comment by foxmask** [comment]
Hi,

I read your post more precisely, and have questions:

* What do you need, to use that project if it covers a part of your needs ? 

* Do you search a tool/soft that automatically synchronizes the data of the device that collects your health state and displays a graph of anything you want ?

* The manufacturer does not provide such a thing ?
if no, how could we get the data from the device ?

If data can be collected, we can try to build another project that follow more precisely your needs (and may be the needs of many more diabetic people)

Just tell me :) 
Regards

**Comment by drfraser** [comment]
Hi,

Sorry to say, I haven't really taken a look at this project yet - I'm getting a MSc in Data Science right now and the work all last year was more than I thought it'd be. And this semester looks worse.

I submitted this issue to provide some suggestions - I guess I was interested to see a web type app that handles the usual functionality of what all the different diabetes related software do. A web app is a lot more ... useful? than some closed source mobile phone app or SaaS system you have to sign up to. For privacy conscious consumers who are not technical, but don't want to be submitting their health data to some corporation, a Django based web site that could be rolled up into a Docker image or AWS free tier based sort of thing would be useful - personal web sites for non-tech people, etc. Or a simple install of Nginx, etc that runs on one's PC. Maybe that is a key idea - how can non-technical people easily install and use the system you are building?

As far as I know, manufacturers of blood glucose meters don't really offer tech specs on how the meters transfer data - closed source Windows drivers etc. With that info, a developer could easily write something to get data from the meter as they see fit. So that is the biggest tech issue I see. I'm sure there is info available somewhere, and at the very least, some hardware reverse engineering to decode the protocol is always possible - I bet someone has, I just haven't looked for it.

I will look at this Django app when I get a chance and give you some more feedback - I have a lot of work this semester, and then it's the dissertation...

**Comment by tylergale** [comment]
I've noticed that there are a lot of projects that add a lot of tracking and smart capabilities for type 1 diabetics on insulin pumps, but not many that cater for us that still use the manual blood tests.  There is significant fragmentation among the various providers of pumps on how data is kept and transferred on these devices, but I've noticed that lately a lot of them appear to be moving to general USB storage device and CSV files (I can provide some files for example) that should theoretically be importable (they are nothing but standard CSV files).

This project is great that it will allow me to enter data from pretty much any device that has an internet connection, but to be able to import a CSV file would be interesting!

**Comment by foxmask** [comment]
Yes that will be wonderful to have that possibility.
If you could provider an exttact of a CVS file i'll be glad to make an import process. 
If you could also give the model of your pump, thus, may be someone else could use the project or would contribute by sharing à CVS file related to his/her pump
Thanks

**Comment by foxmask** [comment]
To be reopened once news info will be provided

**Comment by foxmask** [comment]
I read https://github.com/openaps/openaps/blob/master/README.md and saw that the app can work with devices. As i don't have any, I can't go thurthere more.  If you could provide data from the commands:
```
openaps report invoke
```
or
```
openaps-use pump
```
